### PR TITLE
63b apply settings to menu item page

### LINKED ISSUE #63: Apply settings to menu item page
There are a few settings that were not applied to the item page. They are:
image

Apply these settings on the menu items page.
- [x] Using the extra toppings area on item page already in place enforce the first rule (in the image) by removing that add toppings section when `settingsModel.allowUserToAddToppings` is false, otherwise show it.
- [x] If the above rule is true, then also enforce the allowed amount of toppings that the user might add by blocking the user from adding another topping when max number is reached. Property for this is `settingsModel.maxAmountOfAddons`
- [x] Add a text saying "_Até 2 adicionais permitidos_" between the title and the first topping of the section (where the white line is), where 2 is the `settingsModel.maxAmountOfAddons`

For discussion:
Right now we are offering only additions that are already the item's toppings/sauce. If that's the case maybe it's unnecessary to have an add sauce section. So I was thinking of commenting that section out until we decide if we'll add more things to it later on. What do you think? If you agree, then you also have this task:

- [x] Comment out the add sauce section on item page

### PR DESCRIPTION
**Pull request by ericbraz**
Resolves #63

### CODE REVIEW

**Comment by ericbraz** [comment]
@brunorplima don't approve this

**Comment by brunorplima** [comment]
@ericbraz why?

**Comment by brunorplima** [comment]
@ericbraz Is this PR still supposed to be reviewed or should it be closed?

**Comment by brunorplima** [comment]
@ericbraz ????

**Comment by ericbraz** [comment]
> @ericbraz ????

Delete it

**Pull request closed without merging**
